eureka:
    client:
        service-url:
            defaultZone: http://eureka-sv:8761/eureka
server:
    port: 433
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true